---
title: "Chapter Five HW"
author: "jjh"
editor: visual
---

```{r, include = FALSE}
require(tidyverse)
require(car)
require(ALSM)
require(MASS)
```

| i:       | 1   | 2   | 3   | 4   | 5   | 6   | 7   | 8   | 9   | 10  |
|----------|-----|-----|-----|-----|-----|-----|-----|-----|-----|-----|
| $X_{i}$: | 1   | 0   | 2   | 0   | 3   | 1   | 0   | 1   | 2   | 0   |
| $Y_{i}$: | 16  | 9   | 17  | 12  | 22  | 13  | 8   | 15  | 19  | 11  |

: Question 3.5 Airfreight breakage

```{r, include = TRUE}
airfreight <-
  tibble(
  x = c(1, 0, 2, 0, 3, 1, 0, 1, 2, 0),
  y = c(16, 9, 17, 12, 22, 13, 8, 15, 19, 11)
  )
```

```{r}
airfreight.lm <- lm(y ~ x, data = airfreight)
```

```{r}
airfreight.lm
```

```{r}
summary(airfreight.lm)
```

```{r}
Anova(airfreight.lm, type = "III")
```

**5.6** Refer to **Airfreight breakage** Problem 1.21. Using matrix models,

Find (1) $Y{'}Y$, (2) $X{'}X$, (3) $X{'}Y$.

**(1)**

```{r}
Y_1 = c(16, 9, 17, 12, 22, 13, 8, 15, 19, 11)
```

```{r}
Y = matrix(Y_1)
```

```{r}
Y
```

```{r}
t(Y)%*%Y
```

**(2.)**

```{r}
X = cbind(rep(1, 10), airfreight$x)
```

```{r}
t(X)%*%X
```

**(3.)**

```{r}
t(X)%*%Y
```

**5.25** Refer to **Airfreight breakage** Problem 1.21 and 5.6.

**a.** Using matrix methods, obtain the following:

Find (1) $(X{'}X)^{-1}$, (2) $b$, (3) $e$, (4) $H$, (5) $SSE$, (6) $s^{2}b$, (7) $\hat Y_{h}$ when $X_{h} = 2$, (8) $s^{2}${$\hat Y_{h}$} when $X_{h} = 2$.

**(1)**

```{r}
t(X)%*%X
```

```{r}
solve(t(X)%*%X)
```

```{r}
Y = as.matrix(airfreight$y)
```

**(2.)**

```{r}
(b=solve(t(X)%*%X)%*%(t(X)%*%Y))
```
```{r}
MSE=7.5; (s2.b=MSE*solve(t(X)%*%X))
```
**(4.)**

# Hat matrix

```{r}
(H=X%*%solve(t(X)%*%X)%*%t(X))
```

# Fitted values

```{r}
(Y.hat=X%*%b) 
```

**(4.)**

```{r}
H%*%Y
```

**(3.)**

# Residuals

```{r}
(e=Y-Y.hat) 
```

```{r}
(diag(10)-H)%*%Y
```
**(7.)**

# Estimation of mean response

```{r}
X.h = c(1, 2)
```

```{r}
(Yhat.h=X.h%*%b)
```

```{r}
(s2.Yhat.h=MSE*t(X.h)%*%solve(t(X)%*%X)%*%X.h)
```

**b.** From part (a6), obtain the following: (1) $s^{2}b_{1}$, (2) $s^{2}b_{0}b_{1}$, (3) $s^{2}b_{0}$,


```{r}
MSE=7.5; (s2.b=MSE*solve(t(X)%*%X))
```



**c.**

 ANOVA sums of squares

```{r}
J=matrix(rep(1,100),10,10)
```

```{r}
(SSTO=t(Y)%*%(diag(10)-J/10)%*%Y)
```

```{r}
(SSE=t(Y)%*%(diag(10)-H)%*%Y) 
```

```{r}
(SSR=t(Y)%*%(H-J/10)%*%Y)
```

```{r}
anova(airfreight.lm)
```


